### ISSUE TITLE
ERROR: Failed building wheel for pyahocorasick

### ISSUE THREAD

**Issue by melikekarakaya** [ChongLC/MinimalSetofViralPeptidome-UNIQmin#4]
An error message was shown while installing uniqmin (using the command `pip install uniqmin`). 

 ERROR: Command errored out with exit status 1:
   command: 'c:\users\melike karakaya\miniconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Melike Karakaya\\AppData\\Local\\Temp\\pip-install-0z5780hf\\pyahocorasick_8cfd290885aa49638c57fa408cf92944\\setup.py'"'"'; __file__='"'"'C:\\Users\\Melike Karakaya\\AppData\\Local\\Temp\\pip-install-0z5780hf\\pyahocorasick_8cfd290885aa49638c57fa408cf92944\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Melike Karakaya\AppData\Local\Temp\pip-wheel-w91iq8q5'
       cwd: C:\Users\Melike Karakaya\AppData\Local\Temp\pip-install-0z5780hf\pyahocorasick_8cfd290885aa49638c57fa408cf92944\
  Complete output (50 lines):
  running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Melike Karakaya\AppData\Local\Temp\pip-install-0z5780hf\pyahocorasick_8cfd290885aa49638c57fa408cf92944\setup.py", line 89, in <module>
      setup(
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
      return run_commands(dist)
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
      dist.run_commands()
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\wheel\bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
      _build_ext.run(self)
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
      _build_ext.build_extension(self, ext)
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
      objects = self.compiler.compile(sources,
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
      self.initialize()
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
      vc_env = _get_vc_env(plat_spec)
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
      return _msvc14_get_vc_env(plat_spec)
    File "c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
      raise distutils.errors.DistutilsPlatformError(
  setuptools._distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for pyahocorasick
  Running setup.py clean for pyahocorasick
Failed to build pyahocorasick
Installing collected packages: pyahocorasick, uniqmin
    Running setup.py install for pyahocorasick ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\melike karakaya\miniconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Melike Karakaya\\AppData\\Local\\Temp\\pip-install-0z5780hf\\pyahocorasick_8cfd290885aa49638c57fa408cf92944\\setup.py'"'"'; __file__='"'"'C:\\Users\\Melike Karakaya\\AppData\\Local\\Temp\\pip-install-0z5780hf\\pyahocorasick_8cfd290885aa49638c57fa408cf92944\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Melike Karakaya\AppData\Local\Temp\pip-record-h1xmizm2\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\melike karakaya\miniconda3\Include\pyahocorasick'
         cwd: C:\Users\Melike Karakaya\AppData\Local\Temp\pip-install-0z5780hf\pyahocorasick_8cfd290885aa49638c57fa408cf92944\
    Complete output (6 lines):
    running install
    c:\users\melike karakaya\miniconda3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_ext
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\melike karakaya\miniconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Melike Karakaya\\AppData\\Local\\Temp\\pip-install-0z5780hf\\pyahocorasick_8cfd290885aa49638c57fa408cf92944\\setup.py'"'"'; __file__='"'"'C:\\Users\\Melike Karakaya\\AppData\\Local\\Temp\\pip-install-0z5780hf\\pyahocorasick_8cfd290885aa49638c57fa408cf92944\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Melike Karakaya\AppData\Local\Temp\pip-record-h1xmizm2\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\melike karakaya\miniconda3\Include\pyahocorasick' Check the logs for full command output.

**Comment by ChongLC** [comment]
Dear Melike, 

As there is an issue on pip install pyahocorasick within conda environment, kindly run
```
conda config --add channels conda-forge
conda install pyahocorasick
```
... and restart the kernel before installing the UNIQmin. 

Below, I attached an example: 
![WhatsApp Image 2022-01-20 at 17 11 30](https://user-images.githubusercontent.com/51225708/150397362-96994dab-a8f5-4408-99cc-579fd42d9cbe.jpeg)

![WhatsApp Image 2022-01-20 at 17 11 30 (1)](https://user-images.githubusercontent.com/51225708/150397464-60cc6087-f6b3-497f-8381-52c3480bd19b.jpeg)
